language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

matrix:
  include:
    # Add builds for Conda.
    - python: 2.7
      env: CONDA=1
    - python: 3.5
      env: CONDA=1
    - python: 3.6
      env: CONDA=1
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - HYPOTHESIS_PROFILE=ci

install:
  - source ci/travis-install.sh

script:
  - source ci/travis-build.sh
  - $PIP install cibuildwheel==0.7.1
  - cibuildwheel --output-dir wheelhouse
